# Generated by Django 4.2.1 on 2023-06-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Enter date of birth')),
                ('email', models.EmailField(help_text='Enter email', max_length=254)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Enter type', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Enter country', max_length=20)),
                ('owner', models.CharField(help_text='Enter owner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter code', max_length=20)),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
                ('instruction', models.TextField(help_text='Enter instruction')),
                ('description', models.TextField(help_text='Enter description')),
                ('price', models.IntegerField(help_text='Enter price')),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('medicines_type', models.ForeignKey(help_text='Choose carcass type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.medicinestype')),
                ('supplier', models.ForeignKey(help_text='Choose supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.supplier')),
            ],
        ),
    ]
