# Generated by Django 4.2.1 on 2023-06-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicines_type',
            field=models.ForeignKey(help_text='Choose type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy_app.medicinestype'),
        ),
    ]
